// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:056edb9d-251a-4f27-bf1b-a49f75269766",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_wsvB83Iql",
    "aws_user_pools_web_client_id": "5lfbvff27qliorgv6o0kp5c56v",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://22iml3hayjftvdnzmkuskxhi2i.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
